### ISSUE TITLE
Be Aware - Creator is untrustworthy.

### ISSUE THREAD

**Issue by ElryDeveloper** [NetickNetworking/NetickForUnity#4]
Looking at this reddit posts second image they are trying to bash Fishnet.
Fishnet offers CSP and Lag Compensation, and the implemtation is as easy as it gets.
![image](https://github.com/user-attachments/assets/e25a0623-017d-48c4-b0e8-515a17c36040)
https://www.reddit.com/r/Unity3D/comments/z1p74h/i_released_my_networking_solution_netick_for_free/
Further looking at their post history they posted more lies and fucky stuff:
https://www.reddit.com/r/Unity3D/comments/1djv4vx/netick_2_is_the_only_free_networking_solution_for/
https://www.reddit.com/r/Unity3D/comments/18efw7j/comment/kd9b4a4/
https://www.reddit.com/r/Unity3D/comments/18efw7j/comment/kctt6x3/
https://www.reddit.com/r/Unity3D/comments/18efw7j/comment/kcst7i5/
https://www.reddit.com/r/Unity3D/comments/18efw7j/comment/kcpydtc/
And so many more: https://www.reddit.com/user/Kakr-98/

I would not trust this person.

**Comment by karrarrahim** [comment]
You were reported everywhere you spammed this random list of comments and posts.
